# Generated by Django 4.0 on 2022-03-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='userid',
            new_name='companyid',
        ),
    ]
