# Generated by Django 4.0 on 2022-03-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_userid_branch_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
